---
title: Ryankazokas.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
highlighter: rouge
url: https://ryankazokas.github.io
lsi: false
exclude:
- LICENSE
- CNAME
- README.md
- ".gitignore"
- Gemfile
- Gemfile.lock
